apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb-ss.yaml
  - mongodb-svc.yaml
  - ./network-policies/allow-color-api.yaml

# causa bug sobreescrevendo o seletor ao aplicar a politica de segurança
# commonLabels:
#   app: mongodb
#   project: proj-gke

configMapGenerator:
  - name: mongodb-init-colordb
    files:
      - mongo-init.js